version: '3.4'

services:
  apigwbase:
    image: fuli1001/photography-apigwbase:linux
    build:
      context: .
      dockerfile: Src/ApiGateways/ApiGwBase/Dockerfile
    networks:
      - photonetwork

  userapi:
    image: fuli1001/photography-userapi:linux
    build:
      context: .
      dockerfile: Src/Services/User/User.API/Dockerfile
    networks:
      - photonetwork

  postapi:
    image: fuli1001/photography-postapi:linux
    build:
      context: .
      dockerfile: Src/Services/Post/Post.API/Dockerfile
    networks:
      - photonetwork

  orderapi:
    image: fuli1001/photography-orderapi:linux
    build:
      context: .
      dockerfile: Src/Services/Order/Order.API/Dockerfile
    networks:
      - photonetwork

  notificationapi:
    image: fuli1001/photography-notificationapi:linux
    build:
      context: .
      dockerfile: Src/Services/Notification/Notification.API/Dockerfile
    networks:
      - photonetwork

  manager:
    image: fuli1001/photography-manager:linux
    build:
      context: .
      dockerfile: Src/WebApps/Management/Dockerfile

  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
      
networks:
  photonetwork:
