version: '3.4'

services:
  apigwbase:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Auth__Authority=http://43.225.159.87:5100
      - Auth__Audience=Photography.ApiGateway
      - ServerSettings__ChatServer=N/A
      - ServerSettings__FileServer=N/A
      - ServerSettings__AgoraAppId=N/A
      - ServerSettings__TrtcAppId=N/A
      - ServerSettings__TrtcEnabled=false
    ports:
      - "5101:80"
      
  postapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PostConnection=Server=47.108.194.52;Database=Photography.Post;User Id=fuli;Password=fl511304;
      - Auth__Authority=http://43.225.159.87:5100
      - Auth__Audience=Photography.Post.API
    ports:
      - "5102:80"

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__UserConnection=Server=47.108.194.52;Database=Photography.User;User Id=fuli;Password=fl511304;
      - Auth__Authority=http://43.225.159.87:5100
      - Auth__Audience=Photography.User.API
      - Auth__ClientId=ro.client
      - Auth__ClientSecret=511536EF-F270-4058-80CA-1C89C192F69A
      - Auth__Scope=openid profile Photography.Post.API Photography.User.API Photography.ApiGateway Arise.FileUploadService
    ports:
      - "5103:80"
