version: '3.4'

services:
  apigwbase:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthSettings_Authority=http://43.225.159.87:5100
      - AuthSettings_Audience=Photography.ApiGateway
      - ServerSettings__ChatSocket=47.108.194.52
      - ServerSettings__ChatSocketPort=9022
      - ServerSettings__ChatAPI=47.108.194.52
      - ServerSettings__ChatAPIPort=7899
      - ServerSettings__FileServer=47.108.194.52
      - ServerSettings__FileServerPort=7899
      - ServerSettings__AgoraAppId=CNKSAASDV
      - ServerSettings__TrtcAppId=CDASNMKLVDAS
      - ServerSettings__TrtcEnabled=true
    ports:
      - "5101:80"
      
  postapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PostConnection=Server=47.108.194.52;Database=Photography.Post;User Id=fuli;Password=fl511304;
      - AuthSettings_Authority=http://43.225.159.87:5100
      - AuthSettings_Audience=Photography.Post.API
    ports:
      - "5102:80"

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__UserConnection=Server=47.108.194.52;Database=Photography.User;User Id=fuli;Password=fl511304;
      - AuthSettings__Authority=http://43.225.159.87:5100
      - AuthSettings__Audience=Photography.User.API
      - AuthSettings__ClientId=ro.client
      - AuthSettings__ClientSecret=511536EF-F270-4058-80CA-1C89C192F69A
      - AuthSettings__Scope=openid profile Photography.Post.API Photography.User.API Photography.Order.API Photography.ApiGateway Arise.FileUploadService
      - ServerSettings__ChatSocket=47.108.194.52
      - ServerSettings__ChatSocketPort=9022
      - ServerSettings__ChatAPI=47.108.194.52
      - ServerSettings__ChatAPIPort=7899
      - ServerSettings__FileServer=47.108.194.52
      - ServerSettings__FileServerPort=7899
      - ServerSettings__AgoraAppId=CNKSAASDV
      - ServerSettings__TrtcAppId=CDASNMKLVDAS
      - ServerSettings__TrtcEnabled=true
    ports:
      - "5103:80"

  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__UserConnection=Server=47.108.194.52;Database=Photography.Order;User Id=fuli;Password=fl511304;
      - AuthSettings__Authority=http://43.225.159.87:5100
      - AuthSettings__Audience=Photography.Order.API
    ports:
      - "5104:80"
