version: '3.4'

services:
  apigwbase:
    image: photography-apigwbase
    build:
      context: .
      dockerfile: Src/ApiGateways/ApiGwBase/Dockerfile
    networks:
      - photonetwork

  userapi:
    image: photography-userapi
    build:
      context: .
      dockerfile: Src/Services/User/User.API/Dockerfile
    networks:
      - photonetwork

  postapi:
    image: photography-postapi
    build:
      context: .
      dockerfile: Src/Services/Post/Post.API/Dockerfile
    networks:
      - photonetwork

  orderapi:
    image: photography-orderapi
    build:
      context: .
      dockerfile: Src/Services/Order/Order.API/Dockerfile
    networks:
      - photonetwork

  notificationapi:
    image: photography-notificationapi
    build:
      context: .
      dockerfile: Src/Services/Notification/Notification.API/Dockerfile
    networks:
      - photonetwork

  manager:
    image: photography-manager
    build:
      context: .
      dockerfile: Src/WebApps/Management/Dockerfile

  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
      
networks:
  photonetwork:
