name: Apigwbase CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  cd:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t photography-apigwbase .
      - name: Tags
        run: |
          docker tag photography-apigwbase ${{ secrets.DOCKER_USER }}/photography-apigwbase:${{ github.sha }}
          docker tag photography-apigwbase ${{ secrets.DOCKER_USER }}/photography-apigwbase:linux
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/photography-apigwbase:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/photography-apigwbase:linux
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker stack deploy --compose-file ~/photo/deploy/photo/docker-compose.yml --compose-file ~/photo/deploy/photo/docker-compose.override.yml photo
          host: ${{ secrets.TEST_SERVER }}
          username: ${{ secrets.TEST_SERVER_USER }}
          privateKey: ${{ secrets.ID_RSA }}