name: Photography photo-share CI/CD (Test)

on:
  push:
    branches:
      - test
    paths:
      - 'Src/photo-share/**'
  pull_request:
    branches:
      - test
    paths:
      - 'Src/photo-share/**'
      
jobs:
  cd:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build
        run: docker build -f ./Src/photo-share/Dockerfile -t photography-photoshare .
        
      - name: Tags
        run: |
          docker tag photography-photoshare ${{ secrets.DOCKER_USER }}/photography-photoshare:${{ github.sha }}
          docker tag photography-photoshare ${{ secrets.DOCKER_USER }}/photography-photoshare:linux
          
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/photography-photoshare:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/photography-photoshare:linux