name: photo-share (Test)

on:
  push:
    branches:
      - test
    paths:
      - 'Src/WebApps/photo-share/**'
  pull_request:
    branches:
      - test
    paths:
      - 'Src/WebApps/photo-share/**'
      
jobs:
  cd:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Replace config.prod.json with config.dev.json
        run: cp ./Src/WebApps/photo-share/src/assets/config/config.dev.json ./Src/WebApps/photo-share/src/assets/config/config.prod.json
        
      - name: Build
        run: docker build -f ./Src/WebApps/photo-share/Dockerfile -t photography-photoshare .
        
      - name: Tags
        run: |
          docker tag photography-photoshare ${{ secrets.DOCKER_USER }}/photography-photoshare:${{ github.sha }}
          docker tag photography-photoshare ${{ secrets.DOCKER_USER }}/photography-photoshare:linux
          
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/photography-photoshare:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/photography-photoshare:linux
          
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker service update --image ${{ secrets.DOCKER_USER }}/photography-photoshare:linux
          host: ${{ secrets.TEST_SERVER }}
          username: ${{ secrets.TEST_SERVER_USER }}
          privateKey: ${{ secrets.ID_RSA }}